server:
  port: 5011
  shutdown: graceful

management:
  endpoints:
    web:
      base-path: /api/actuator
      exposure:
        include: '*' # 모든 Actuator 엔드포인트 웹 노출
  info:
    git:
      mode: full

spring:
  application:
    name: catalog-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:15432/postgres}
    # 프로퍼티(환경변수)가 존재하지 않을 때 기본값(Fallback)으로 postgres를 사용
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}

catalog:
  page-size: 10
