server:
  port: 5010
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: '*' # 모든 Actuator 엔드포인트 웹 노출
  info:
    git:
      mode: full

spring:
  application:
    name: catalog-service

